### ISSUE TITLE
can not create SQLiteConnector.nupkg

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/TE2000_TcHMI_AdvancedServerExtension#1]
Hello
can not create SQLiteConnector.nupkg, error TcHmiSrvExtNet.Core.....
or if they can send the SQLiteConnector.nupkg file
I don't know how to fix it, any help is welcome
![Beckhoff_TcHmiSrvExtNet Core dll_foto1](https://user-images.githubusercontent.com/53791834/142233291-5fff4577-3030-4457-a5b7-4f11d68570cb.PNG)

thanks you.

**Comment by ZDaulton** [comment]
This is due to the .dll version. This sample uses TchmiSrvExtNet.Core 1.3.0.0

https://github.com/Beckhoff-USA-Community/TE2000_TcHMI_AdvancedServerExtension/blob/master/SQLiteConnector/SQLiteConnector.csproj#L83

I will update the readme to include this requirement. TcHmi 1.12.752.0 includes this core dll.

**Comment by runtimevic** [comment]
> This is due to the .dll version. This sample uses TchmiSrvExtNet.Core 1.3.0.0
> 
> https://github.com/Beckhoff-USA-Community/TE2000_TcHMI_AdvancedServerExtension/blob/master/SQLiteConnector/SQLiteConnector.csproj#L83
> 
> I will update the readme to include this requirement. TcHmi 1.12.752.0 includes this core dll.

Hello,
 I have already solved it
closed issue, thanks you.
